server:
  port: 5003

spring:
  rabbitmq:
    addresses: localhost
  data:
    elasticsearch:
      host: localhost
      ## to fill if authentication is needed
      # user:
      # password:      

backing-services:
  case-server:
    base-uri: http://localhost:5000
  geo-data-server:
    base-uri: http://localhost:8087
  report-server:
    base-uri: http://localhost:5028
  network-store-server:
    base-uri: http://localhost:8080/
