server:
  port: 5003
  forward-headers-strategy: framework

spring:
  application:
    name: network-network-conversion-server
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 103MB
  data:
    elasticsearch:
      enabled: false
      host: localhost
      port: 9200

network-store-server:
  preloading-strategy: COLLECTION
  base-uri: http://localhost:8080/

backing-services:
  case-server:
    base-uri: http://localhost:5000
  geo-data-server:
    base-uri: http://localhost:8087
  report-server:
    base-uri: http://localhost:5028

management:
  health:
    solr:
      enabled: false



