name: Docker Deploy

on: workflow_dispatch

jobs:
  run-deploy:
    uses: powsybl/github-ci/.github/workflows/manual-dockerdeploy-backend-app-generic.yml@3ed0caeb3395e55868884f466d726ddaee877850
    with:
      dockerImage: docker.io/powsybl/network-conversion-server
      dockerUsername: powsyblci
    secrets:
      DOCKER_RELEASE: ${{ secrets.DOCKER_RELEASE }}
